### PR TITLE
Update m2wr.xacro

### LINKED ISSUE #1: Make the wheels bigger
wheels increase by 10%

### PR DESCRIPTION
**Pull request by gyanchith28**
Change in radius as well as mass.

### CODE REVIEW

**Comment by Blackcipher101** [comment]
Nice one always make sure to link the issue which you are trying to solve
I will link it for now

**Comment by Blackcipher101** [comment]
And I asked to increase the radius only :P add that commit Till that time this will be assigned to you

**Comment by gyanchith28** [comment]
Updated the radius value as given in #1

**Comment by Blackcipher101** [comment]
Thanks and Happy hackoctober

**Comment by gyanchith28** [comment]
Happy Hacktober to u too :-p

**Pull request merged**
